# List of all available tickers
FRENCH_TICKERS =    ["AKOM.PA", "AFME.PA", "AF.PA", "AI.PA", "AIR.PA", "AKW.PA", "AAA.PA", "ABIO.PA", "ALD.PA", "CDA.PA", 
                    "ALO.PA", "LTA.PA", "ALTA.PA", "AREIT.PA", "ATE.PA", "ALTUR.PA", "AMPLI.PA", "AMUN.PA", "ANTIN.PA", 
                    "APAM.PA", "APM.PA", "ARAMI.PA", "MT.PA", "ARG.PA", "AKE.PA", "ARTE.PA", "PRC.PA", "ARTO.PA", "ASY.PA",
                    "ATEME.PA", "ATLD.PA", "ATO.PA", "AUB.PA", "AUGR.PA", "AURE.PA", "AURS.PA", "AVT.PA", "CS.PA", "AXW.PA",
                    "BAIN.PA", "BALYO.PA", "BUI.PA", "BASS.PA", "BLC.PA", "BLV.PA", "BEN.PA", "BB.PA", "BIG.PA", "BIM.PA",
                    "BLEE.PA", "BNP.PA", "BOI.PA", "BOL.PA", "BON.PA", "BOTHE.PA", "BSD.PA", "EN.PA", "BVI.PA", "BUR.PA",
                    "CAT31.PA", "CAFO.PA", "CBDG.PA", "CAP.PA", "CARM.PA", "CARP.PA", "CA.PA", "CO.PA", "CAS.PA", "CATG.PA",
                    "CTRG.PA", "CATR.PA", "CBOT.PA", "CGM.PA", "CYAD.PA", "CFI.PA", "CGG.PA", "CGGBT.PA", "CRI.PA", "CHSR.PA",
                    "CDI.PA", "CIB.PA", "CLA.PA", "COM.PA", "CNV.PA", "COFA.PA", "COH.PA", "RE.PA", "ODET.PA", "COUR.PA",
                    "COV.PA", "COVH.PA", "CRAP.PA", "CRAV.PA", "CRBP2.PA", "CIV.PA", "CRLA.PA", "CRLO.PA", "CMO.PA", "CNF.PA",
                    "CCN.PA", "CAF.PA", "CRSU.PA", "CRTO.PA", "ACA.PA", "CROS.PA", "SX.PA", "BN.PA", "AM.PA", "DSY.PA", "DBV.PA",
                    "DEE.PA", "DEEW.PA", "DEEZR.PA", "DEEZW.PA", "DKUPL.PA", "DBG.PA", "DGE.PA", "DMSIM.PA", "DPAM.PA", "EDEN.PA", "EDF.PA", "GID.PA", "FGR.PA",
                    "EKI.PA", "ELEC.PA", "EEM.PA", "ELIOR.PA", "ELIS.PA", "ENGI.PA", "EQS.PA", "ERA.PA", "ERYP.PA", "ESI.PA", "ESP.PA", "EL.PA", "ES.PA", 
                    "EFI.PA", "RF.PA", "KINGS.PA", "KINGW.PA", "EUR.PA", "EAPI.PA", "ERF.PA", "ENX.PA", "ETL.PA", "EGR.PA", "EXN.PA", "EXE.PA", 
                    "EXPL.PA", "EO.PA", "FAYE.PA", "FDJ.PA", "FCMC.PA", "FALG.PA", "SACI.PA", "ORIA.PA", "FGA.PA", "BERR.PA", "EBPF.PA", "FOAF.PA",
                    "FINM.PA", "FNTS.PA", "FIPP.PA", "FNAC.PA", "LEBL.PA", "EURS.PA", "INEA.PA", "FLY.PA", "SPEL.PA", "FORE.PA", "FORSE.PA",
                    "FDE.PA", "FREY.PA", "GALIM.PA", "GAM.PA", "GEA.PA", "GFC.PA", "GNE.PA", "GENX.PA", "GNRO.PA", "GNFT.PA", "GV.PA",
                    "SIGHT.PA", "GET.PA", "GLO.PA", "GPE.PA", "GRVO.PA", "CEN.PA", "FLO.PA", "GOE.PA", "IRD.PA", "GJAJ.PA", "PARP.PA",
                    "SFPI.PA", "GTBP.PA", "GTT.PA", "GBT.PA", "GUI.PA", "PIG.PA", "HDF.PA", "RMS.PA", "HEXA.PA", "HCO.PA", "HOLN.PA",
                    "HDP.PA", "ICAD.PA", "IDL.PA", "IDIP.PA", "NK.PA", "IMDA.PA", "INFE.PA", "INF.PA", "IPH.PA", "ITP.PA", "ITXT.PA", 
                    "IVA.PA", "IPN.PA", "IPS.PA", "ITE.PA", "JBOG.PA", "JCQ.PA", "DEC.PA", "KOF.PA", "KER.PA", "LI.PA", "KORI.PA", "OR.PA",
                    "LACR.PA", "MMB.PA", "LAT.PA", "LPE.PA", "LOUP.PA", "LBON.PA", "LSS.PA", "LR.PA", "LHYFE.PA", "LIN.PA", "FII.PA", "LNA.PA",
                    "LBIRD.PA", "MC.PA", "LYS.PA", "MRM.PA", "MAAT.PA", "MDM.PA", "MALT.PA", "MTU.PA", "MAN.PA", "IAM.PA", "MKEA.PA", "MAU.PA",
                    "MBWS.PA", "MBWBT.PA", "MBWSZ.PA", "MCPHY.PA", "EDI.PA", "MEDCL.PA", "MEMS.PA", "MERY.PA", "MRK.PA", "MRN.PA", "METEX.PA",
                    "MMT.PA", "ML.PA", "MUN.PA", "MONC.PA", "MONT.PA", "MHM.PA", "NACON.PA", "NANO.PA", "NAVYA.PA", "NEOEN.PA", "NRO.PA",
                    "NEX.PA", "NXI.PA", "NEXTS.PA", "NHOA.PA", "COX.PA", "NOKIA.PA", "NR21.PA", "NRG.PA", "SBT.PA", "OLG.PA", "ORA.PA",
                    "ORAP.PA", "ORAPB.PA", "OREGE.PA", "ORP.PA", "OSE.PA", "OVH.PA", "PID.PA", "PAR.PA", "PARRO.PA", "PABSA.PA", "PABSB.PA",
                    "PSAT.PA", "PAT.PA", "PCA.PA", "RI.PA", "PERR.PA", "PEUG.PA", "VAC.PA", "PVL.PA", "POM.PA", "POXEL.PA", "PREC.PA", "PROAC.PA",
                    "PWG.PA", "PUBBS.PA", "PUB.PA", "QDT.PA", "RAL.PA", "GDS.PA", "RX.PA", "RCO.PA", "RNO.PA", "RXL.PA", "RBT.PA", "CBR.PA", "CBE.PA",
                    "RBO.PA", "ROTH.PA", "RUI.PA", "SK.PA", "SAF.PA", "SGO.PA", "SABE.PA", "SAMS.PA", "SAN.PA", "DIM.PA", "SAVE.PA", "CBSM.PA", "SLB.PA",
                    "SU.PA", "SCR.PA", "SCHP.PA", "SGRO.PA", "SLCO.PA", "SELER.PA", "SEFER.PA", "SESG.PA", "SESL.PA", "SRP.PA", "SII.PA", "SMCP.PA", "SMTPC.PA",
                    "SFCA.PA", "GLE.PA", "SW.PA", "SEC.PA", "SOG.PA", "SOI.PA", "LOCAL.PA", "S30.PA", "SOLB.PA", "SO.PA", "SOP.PA", "SPIE.PA", "SQI.PA", "DPT.PA",
                    "STF.PA", "STLA.PA", "STM.PA", "SWP.PA", "SDG.PA", "TKTT.PA", "TAYN.PA", "TECBS.PA", "TCH.PA", "TE.PA", "TEP.PA", "TVRB.PA", "TRACT.PA", "TERBS.PA",
                    "TFI.PA", "TFF.PA", "HO.PA", "THEP.PA", "TKO.PA", "TIPI.PA", "TITC.PA", "TTE.PA", "EC.PA", "TOUP.PA", "EIFF.PA", "TNG.PA", "TRAN.PA", "TRANW.PA",
                    "TRI.PA", "UBI.PA", "URW.PA", "UNBL.PA", "UFF.PA", "FPG.PA", "FR.PA", "VK.PA", "VKBS.PA", "VLA.PA", "VIE.PA", "VRLA.PA", "VMX.PA", "VETO.PA", "VCT.PA",
                    "VIL.PA", "RIN.PA", "DG.PA", "VIRP.PA", "VTR.PA", "VIV.PA", "VLTSA.PA", "VRAP.PA", "WAGA.PA", "WAVE.PA", "MF.PA", "WLN.PA", "XFAB.PA", "XIL.PA", "CV.PA"]

NOT_WORKING =       ["ABO.PA", "AAC.PA", "AACW.PA", "AELIS.PA"]

WORKED =            ["2CRSI.PA", "AB.PA", "ABCA.PA", "ABEO.PA", "ABNX.PA", "ABVX.PA", "ABLD.PA", "ACAN.PA", 
                    "AC.PA", "EOS.PA", "ATI.PA", "ALDV.PA", "ADOC.PA", "ADP.PA", "ADUX.PA", "ADVI.PA"]