# List of all available tickers
SBF120 = ["ALU.PA", "AI.PA", "AIR.PA", "CS.PA", "ALO.PA", "AC.PA", "AF.PA", "ALEHT.PA", "SIPH.PA", "OSI.PA", "MT.PA",
          "CAFO.PA", "RMS.PA", "MLMAB.PA", "CDA.PA", "ATO.PA", "ATA.PA", "ALT.PA", "ALOCT.PA", "ALMDG.PA", "ALAST.PA",
          "ADP.PA", "ZC.PA", "XIL.PA", "BNP.PA", "BN.PA", "BAIN.PA", "EN.PA", "ML.PA", "DSY.PA", "DP.PA", "EDF.PA",
          "SMTPC.PA", "MLFER.PA", "EDL.PA", "TAM.PA", "MLMAI.PA", "FDR.PA", "DVT.PA", "DPT.PA", "DGM.PA", "DBV.PA",
          "CBSM.PA", "BSD.PA", "ODET.PA", "MLTRA.PA", "MLTED.PA", "MLSHD.PA", "MLNV.PA", "MLLEM.PA", "MLHK.PA",
          "MLEAU.PA",
          "MLDAM.PA", "MLCMB.PA", "MLCFM.PA", "MALA.PA", "HDP.PA", "GUYD.PA", "FDL.PA", "SEV.PA", "ERF.PA", "EO.PA",
          "EI.PA", "CBE.PA", "SU.PA", "ERSC.PA", "ENGI.PA", "ELIOR.PA", "ECP.PA", "VIE.PA", "UBI.PA", "SESL.PA",
          "RF.PA",
          "GPE.PA", "FGR.PA", "ES.PA", "ERYP.PA", "EOS.PA", "EKI.PA", "EDEN.PA", "ALSAS.PA", "ALGEM.PA", "ALESK.PA",
          "MLCVG.PA", "PUB.PA", "OR.PA", "SAN.PA", "SAFT.PA", "SAF.PA", "GLE.PA", "CRTO.PA", "VIV.PA", "SOI.PA",
          "VRAP.PA",
          "UL.PA", "TKTT.PA", "TCH.PA", "SOP.PA", "QUA.PA", "MC.PA", "MAU.PA", "ILD.PA", "HO.PA", "FR.PA", "FP.PA",
          "CAF.PA", "VK.PA", "VIRP.PA", "VAC.PA", "UG.PA", "THEP.PA", "TES.PA", "SX.PA", "SW.PA", "STAL.PA", "SGO.PA",
          "RXL.PA", "RI.PA", "RCO.PA", "PARRO.PA", "ORA.PA", "NEO.PA", "MLSML.PA", "MGIC.PA", "KER.PA", "ITXT.PA",
          "ICAD.PA", "HIM.PA", "HBW.PA", "HAV.PA", "GDS.PA", "FLY.PA", "FLE.PA", "FII.PA", "COX.PA", "CAP.PA", "CA.PA",
          "BVI.PA", "BB.PA", "VRNL.PA", "TRI.PA", "TOUP.PA", "TER.PA", "TEC.PA", "SY.PA", "SWP.PA", "STF.PA", "SOA.PA",
          "SEC.PA", "SBT.PA", "RNO.PA", "QTE.PA", "PIX.PA", "PIG.PA", "OPN.PA", "NK.PA", "NANO.PA", "MON.PA", "MMT.PA",
          "MLSTR.PA", "MLSIM.PA", "MLRAM.PA", "MLNOV.PA", "MLHBB.PA", "MLCNT.PA", "MLCET.PA", "MFG.PA", "MF.PA",
          "MERY.PA",
          "MED.PA", "MAGIS.PA", "LBON.PA", "LACR.PA", "KN.PA", "JBOG.PA", "ITE.PA", "IPS.PA", "IPN.PA", "IPH.PA",
          "IMPL.PA", "IML.PA", "HONV.PA", "GTT.PA", "GFT.PA", "GFI.PA", "GFC.PA", "GEA.PA", "GBT.PA", "FREY.PA",
          "FPN.PA",
          "FPG.PA", "FNTS.PA", "FNAC.PA", "FFP.PA", "FEM.PA", "FBEL.PA", "FAYE.PA", "CIV.PA", "CGM.PA", "CGG.PA",
          "CCA.PA",
          "BOL.PA", "BELI.PA", "AREVA.PA", "ALUMS.PA", "ALTUT.PA", "ALTRA.PA", "ALTER.PA", "ALQGC.PA", "ALORO.PA",
          "ALINN.PA", "ALHVS.PA", "ALGEN.PA", "ALCLS.PA", "ALCLA.PA", "ALBUD.PA", "ALALO.PA", "ALADO.PA", "AKA.PA",
          "ACA.PA", "ABIO.PA", "ZIF.PA", "VLAP.PA", "VET.PA", "VCT.PA", "UFF.PA", "UDIS.PA", "TNG.PA", "MLFIH.PA",
          "HSB.PA", "MSTY.PA", "GJAJ.PA", "DEC.PA", "MLEST.PA", "JCQ.PA", "MLJAN.PA", "MLKRI.PA", "MLKIM.PA", "KOF.PA",
          "KEY.PA", "ALKEY.PA", "LAX.PA", "PM.PA", "MLSEQ.PA", "MLSMP.PA", "STM.PA", "CSTM.PA", "NXI.PA", "NUM.PA",
          "NRO.PA", "NEX.PA", "OXI.PA", "ORP.PA", "ORAP.PA", "ONXEO.PA", "OLG.PA", "MLOPT.PA", "MLONE.PA", "ALONC.PA",
          "ALODI.PA", "ALOCA.PA", "OSE.PA", "AGTA.PA", "SQI.PA", "RX.PA", "CATR.PA", "MRK.PA", "IFF.PA", "HXL.PA",
          "FORDP.PA", "ALUCR.PA", "RIN.PA", "MLVER.PA", "MLGEQ.PA", "LTE.PA", "GV.PA", "DGNV.PA", "DG.PA", "CRAV.PA",
          "ALVXM.PA", "ALVMG.PA", "ALVEL.PA", "ALVDM.PA", "ALVDI.PA", "MLVAL.PA", "MLVES.PA", "VIAD.PA", "MLANT.PA",
          "MCNV.PA", "MLPHW.PA", "MBWS.PA", "ALWEB.PA", "IGE.PA", "XPO.PA", "GND.PA", "MLDYH.PA", "MLZAM.PA",
          "STAGR.PA",
          "ZCNV.PA", "MLDUR.PA", "CV.PA", "ABCA.PA", "ABBV.PA", "AB.PA", "MLABC.PA", "ABVX.PA", "MLACP.PA", "CIB.PA",
          "ACAN.PA", "ALACI.PA", "ALACR.PA", "MLACT.PA", "MLLEO.PA", "ACNV.PA", "ATI.PA", "ALP.PA", "ALADM.PA",
          "ADVI.PA",
          "ALPAT.PA", "ADV.PA", "ADOC.PA", "ALADA.PA", "ADI.PA", "FGA.PA", "MLNOT.PA", "BOAF.PA", "AFO.PA", "MLAFT.PA",
          "FOAF.PA", "CRLO.PA", "CRBP2.PA", "CNF.PA", "CAT31.PA", "ALAGR.PA", "CMO.PA", "AGCR.PA", "MLBRO.PA",
          "MLMLT.PA",
          "CRSU.PA", "CRLA.PA", "MLAAH.PA", "MLIFE.PA", "MLAGI.PA", "ALFBA.PA", "AKE.PA", "MLAKD.PA", "AKENV.PA",
          "ALCOI.PA", "ALATP.PA", "LTA.PA", "CRAP.PA", "ATE.PA", "ALUCI.PA", "ALTHE.PA", "ALTEV.PA", "ALSPO.PA",
          "ALSIM.PA", "ALSDL.PA", "ALS30.PA", "ALRGR.PA", "ALNEV.PA", "ALNBT.PA", "ALLOG.PA", "ALIOX.PA", "ALIMO.PA",
          "ALICR.PA", "ALHIT.PA", "ALHEO.PA", "ALGOW.PA", "ALGLD.PA", "ALGEP.PA", "ALFRE.PA", "ALFPC.PA", "ALEUP.PA",
          "ALENT.PA", "ALDEI.PA", "ALCYB.PA", "ALCOR.PA", "ALCJ.PA", "ALCAR.PA", "ALAUP.PA", "ALANT.PA", "AREIT.PA",
          "ALTRO.PA", "ALNXT.PA", "ALHPC.PA", "ALMER.PA", "ALSGD.PA", "ALECR.PA", "ALPHX.PA", "ALREW.PA", "ALINT.PA",
          "ALTTI.PA", "ALMGI.PA", "ALEZV.PA", "ALIDS.PA", "ALMTH.PA", "ALMED.PA", "ALHOL.PA", "ALI2S.PA", "ALIMR.PA",
          "ALREA.PA", "ALPHY.PA", "ALRIC.PA", "ALPJT.PA", "ALBFR.PA", "ALMNG.PA", "ALODS.PA", "ALINS.PA", "ALDBT.PA",
          "ALBLD.PA", "ALSFT.PA", "ALBRS.PA", "ALKDY.PA", "ALIVA.PA", "ALDBL.PA", "ALBRI.PA", "ALBI.PA", "ALMDT.PA",
          "ALMOU.PA", "ALBIO.PA", "ALAQU.PA", "ALFST.PA", "ALOBR.PA", "ALTVO.PA", "ALDEL.PA", "ALDAR.PA", "ALDR.PA",
          "ALTXC.PA", "ALCRB.PA", "ALCOG.PA", "ALHER.PA", "ALUT.PA", "ALSOA.PA", "ALLIX.PA", "ALSER.PA", "ALWED.PA",
          "ALMIL.PA", "ALDMO.PA", "ALMAK.PA", "ALHYG.PA", "ALSPW.PA", "ALDLS.PA", "ALLEX.PA", "ALBLU.PA", "ALGBE.PA",
          "ALLMG.PA", "ALMAS.PA", "ALMET.PA", "ALENR.PA", "ALVIV.PA", "ALDOL.PA", "ALLP.PA", "ALGIL.PA", "ALCRM.PA",
          "ALOSP.PA", "ALMLB.PA", "ALHIO.PA", "ALISC.PA", "ALANV.PA", "ALPCI.PA", "ALSEN.PA", "ALSTW.PA", "ALMIC.PA",
          "ALCES.PA", "ALCOF.PA", "ALA2M.PA", "ALBDM.PA", "ALSOL.PA", "ALBPS.PA", "ALGEV.PA", "ALTA.PA", "ALVER.PA",
          "ALPDX.PA", "ALMDW.PA", "ALDRV.PA", "ALPGG.PA", "ALNSE.PA", "ALNOV.PA", "ALTRI.PA", "ALESA.PA", "ALFIL.PA",
          "ALPLA.PA", "ALGCM.PA", "ALROC.PA", "ALTUR.PA", "ALDIE.PA", "ALVIA.PA", "ALPOU.PA", "ALWEC.PA", "ALM.PA",
          "ALLHB.PA", "ALDV.PA", "ALEO2.PA", "ALPRI.PA", "ALGAU.PA", "ALSIP.PA", "ALFOC.PA", "ALEMV.PA", "ALTLX.PA",
          "ALEUA.PA", "ALGIS.PA", "ALPRO.PA", "AMUN.PA", "AMEBA.PA", "AM.PA", "AMPLI.PA", "MLARD.PA", "AML.PA",
          "ROSA.PA",
          "PSAT.PA", "PROL.PA", "PAOR.PA", "PERR.PA", "MLIMP.PA", "MLHOP.PA", "MLGRC.PA", "GUI.PA", "FIPP.PA", "ETL.PA",
          "EDI.PA", "CO.PA", "BLUE.PA", "BLEE.PA", "MPI.PA", "ANF.PA", "MND.PA", "NSGP.PA", "MLCEC.PA", "MLPSH.PA",
          "MLOLM.PA", "MLAMA.PA", "MLSIC.PA", "ORPNV.PA", "MLETA.PA", "MLHYD.PA", "TNFN.PA", "INFE.PA", "AUGR.PA",
          "RAL.PA", "MLFXO.PA", "FALG.PA", "LLY.PA", "SLB.PA", "STNT.PA", "MLMTD.PA", "MLFRC.PA", "MLCMI.PA", "NRX.PA",
          "MLFMM.PA", "MLTDS.PA", "MLCFD.PA", "SFCA.PA", "SII.PA", "APR.PA", "MLAAT.PA", "MLGAI.PA", "ARTE.PA",
          "ARG.PA",
          "MLART.PA", "MLARO.PA", "JXR.PA", "MLAMY.PA", "ARTO.PA", "PRC.PA", "MLNMA.PA", "ASY.PA", "ASK.PA", "MLVOP.PA",
          "MLAEM.PA", "CNP.PA", "ASP.PA", "ML350.PA", "FATL.PA", "ATEME.PA", "ATONV.PA", "AURE.PA", "AUB.PA", "AURS.PA",
          "AVT.PA", "AVQ.PA", "AWOX.PA", "AXW.PA", "CSNV.PA", "MLAZL.PA", "BLC.PA", "BCRA.PA", "BCAM.PA", "MLGES.PA",
          "BEN.PA", "MLMFI.PA", "MLIOC.PA", "DEXB.PA", "MLV4S.PA", "BERR.PA", "MTU.PA", "DIM.PA", "BIM.PA", "BIG.PA",
          "MLCLI.PA", "MLTBM.PA", "BND.PA", "BNS.PA", "GBB.PA", "BOI.PA", "MLBOK.PA", "CARP.PA", "BON.PA", "ENNV.PA",
          "BOLNV.PA", "MLLB.PA", "MRB.PA", "BUR.PA", "BVINV.PA", "BUI.PA", "MLHMC.PA", "CBDG.PA", "CAS.PA", "CAPLI.PA",
          "CBOT.PA", "CBR.PA", "CCN.PA", "CCE.PA", "CC.PA", "CDI.PA", "CLNV.PA", "CGR.PA", "CEREN.PA", "CEN.PA",
          "MLROU.PA", "CGD.PA", "CFAO.PA", "CFI.PA", "TVRB.PA", "MLTRC.PA", "LHN.PA", "CHSR.PA", "MLFIR.PA", "CHAU.PA",
          "MLCSP.PA", "MLOVE.PA", "CIEM.PA", "MLMAT.PA", "MLTHA.PA", "MLCIO.PA", "FORE.PA", "MLPIV.PA", "VIL.PA",
          "LTAN.PA", "MLCJS.PA", "CNV.PA", "MLFCI.PA", "MLCRO.PA", "CRINV.PA", "CRI.PA", "CRBT.PA", "CROS.PA",
          "MLCTA.PA",
          "CTRG.PA", "MLSIL.PA", "DAN.PA", "IMDA.PA", "MLDHZ.PA", "DLT.PA", "DSYNV.PA", "DRTY.PA", "DBT.PA", "DBG.PA",
          "COM.PA", "MLMGL.PA", "MLSDR.PA", "MLMED.PA", "DLTA.PA", "ULDV.PA", "FDPA.PA", "MLEDR.PA", "DGE.PA",
          "DIREN.PA",
          "MLDIG.PA", "MLDDP.PA", "MLBRI.PA", "DIG.PA", "DNX.PA", "DOMS.PA", "DPAM.PA", "DUC.PA", "DUPP.PA", "MLEDS.PA",
          "PVL.PA", "FCMC.PA", "MLDYN.PA", "MLDYX.PA", "MLEAS.PA", "EEM.PA", "ECASA.PA", "EC.PA", "MLECO.PA",
          "MLEDU.PA",
          "EDENV.PA", "EFI.PA", "GID.PA", "EINV.PA", "EIFF.PA", "ELIS.PA", "ELEC.PA", "ELE.PA", "GNE.PA", "SUNV.PA",
          "EPS.PA", "TONN.PA", "ELINV.PA", "EMG.PA", "SCHP.PA", "MLEES.PA", "MCPHY.PA", "ENX.PA", "EOSI.PA", "MLEMG.PA",
          "EONV.PA", "EXPL.PA", "ERA.PA", "ERFNV.PA", "ESI.PA", "MLEBX.PA", "MLHIN.PA", "PAT.PA", "MLCAC.PA",
          "MLERO.PA",
          "MLERI.PA", "EURS.PA", "EUCAR.PA", "GET.PA", "MLMCE.PA", "MLITG.PA", "EUR.PA", "MLEVE.PA", "GLO.PA",
          "METEX.PA",
          "EXE.PA", "EXAC.PA", "MLHYE.PA", "MLMEX.PA", "LEY.PA", "FAUV.PA", "MLFAC.PA", "MFC.PA", "MALT.PA", "FED.PA",
          "FINM.PA", "NOKIA.PA", "ORIA.PA", "FIM.PA", "FLO.PA", "FMU.PA", "LEBL.PA", "INEA.PA",
          "MLCFI.PA",
          "SPEL.PA", "LFVE.PA", "MLVIN.PA", "FPNV.PA", "THER.PA", "TFF.PA", "SOG.PA", "SOFR.PA", "SO.PA", "SCDU.PA",
          "SFT.PA", "SFBS.PA", "SDG.PA", "SCR.PA", "SAMS.PA", "SABE.PA", "RIB.PA", "RCF.PA", "PSB.PA", "MUN.PA",
          "MRM.PA",
          "MMB.PA", "MLVST.PA", "MLTRO.PA", "MLSTM.PA", "MLPPI.PA", "MLPOL.PA", "MLPFX.PA", "MLNLF.PA", "MLMON.PA",
          "MLLEA.PA", "MLIML.PA", "MLIDS.PA", "MLGEO.PA", "MLCOR.PA", "LSS.PA", "LR.PA", "LPE.PA", "LOCAL.PA", "LD.PA",
          "LAF.PA", "ITS.PA", "ITP.PA", "INSD.PA", "INN.PA", "ING.PA", "IDIP.PA", "HF.PA", "GTCL.PA", "GOE.PA",
          "GLENV.PA",
          "GECP.PA", "GDMS.PA", "GAM.PA", "FTRN.PA", "COUR.PA", "COH.PA", "MLLOI.PA", "MLIFC.PA", "MLCOU.PA",
          "MLUSG.PA",
          "COFA.PA", "MLRIV.PA", "GENX.PA", "MLFTI.PA", "MLLED.PA", "INF.PA", "LAN.PA", "MLSAT.PA", "RIA.PA", "SK.PA",
          "MLSRP.PA", "MLQUD.PA", "OREGE.PA", "MLUNT.PA", "MLARI.PA", "MLAUD.PA", "MLGAL.PA", "UNBL.PA", "NRG.PA",
          "SPIE.PA", "MLCMG.PA", "MKEA.PA", "TXCL.PA", "LNA.PA", "PHA.PA", "GNFT.PA", "MLPLC.PA", "MLCOL.PA",
          "GBTNV.PA",
          "SESNV.PA", "VLTSA.PA", "ROTH.PA", "RUI.PA", "MEMS.PA", "GRVO.PA", "MLPVG.PA", "MLMII.PA",
          "MLPAC.PA", "MLCHP.PA", "KORI.PA", "TVLY.PA", "RBT.PA", "MLMUL.PA", "MLGRD.PA", "MLSBT.PA", "MLNEO.PA",
          "MRNNV.PA", "POXEL.PA", "PCA.PA", "FREDS.PA", "MLGLO.PA", "RXLNV.PA", "PREC.PA", "MLTEK.PA", "POM.PA",
          "DEVR.PA",
          "TFINV.PA", "IDL.PA", "CATG.PA", "MLJSA.PA", "LAT.PA", "VDLO.PA", "PAR.PA", "PGP.PA", "MLIDP.PA", "MLGEL.PA",
          "GTO.PA", "GIRO.PA", "MLGCR.PA", "MLUMH.PA", "HCO.PA", "HERIG.PA", "HIPAY.PA", "MLHTT.PA", "MLION.PA",
          "MLTMT.PA", "MLMHO.PA", "IAM.PA", "MLIPP.PA", "SSI.PA", "MLIPY.PA", "MLSNT.PA", "VIT.PA", "ITL.PA",
          "DECNV.PA",
          "KAZI.PA", "KERNV.PA", "LI.PA", "LCO.PA", "LDL.PA", "LNC.PA", "MLLCS.PA", "LOUP.PA", "MLLSK.PA", "SESG.PA",
          "ORC.PA", "MCLC.PA", "MLSKN.PA", "MLNEI.PA", "MLWEY.PA", "MLUMG.PA", "MLHOT.PA", "MLORC.PA", "MLSEC.PA",
          "MLMOV.PA", "MLCHE.PA", "MLNES.PA", "MLTEA.PA", "MLHCF.PA", "MLBAT.PA", "MLMAD.PA", "MLCSV.PA", "MLVIS.PA",
          "MLSOL.PA", "MLPHO.PA", "MLMUT.PA", "MLWTT.PA", "MLONL.PA", "MLDEX.PA", "MLOSA.PA", "MLTRS.PA", "MLFDV.PA",
          "MLPPF.PA", "MLMNR.PA", "MLPRI.PA", "MLSUM.PA", "MLPRO.PA", "MLCLP.PA", "MLDTB.PA", "MLAAE.PA", "MLATV.PA",
          "MLSOC.PA", "MLPGO.PA", "MLUNI.PA", "MONC.PA", "MONT.PA", "MRN.PA", "GREV.PA", "NXTV.PA", "NERG.PA", "NTG.PA",
          "SACI.PA", "SAFOR.PA", "PARP.PA", "RUSAL.PA", "RUIDS.PA", "RLL.PA", "ROD.PA", "RUINV.PA", "VALE3.PA",
          "SDT.PA",
          "SFPI.PA", "SGONV.PA", "SRP.PA", "TAYN.PA", "TFI.PA", "TIPI.PA", "TOU.PA", "VLA.PA", "VETO.PA", "VIA.PA",
          "WLN.PA", "RE.PA", "SPI.PA", "HOP.PA", "INFY.PA", "LIN.PA", "MAN.PA", "SANNV.PA", "SAVE.PA",
          "SEFER.PA", "SELER.PA", "SEQ.PA"]

SBF120.sort()
SBF120[0] = "AIR.PA"