# Generated by Django 4.0.6 on 2022-07-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('symbol', models.CharField(max_length=10)),
                ('slug', models.SlugField()),
                ('financial_url', models.CharField(max_length=60)),
                ('per_values', models.TextField(null=True)),
                ('roa_values', models.TextField(null=True)),
                ('roe_values', models.TextField(null=True)),
                ('bna_values', models.TextField(null=True)),
                ('bvps_values', models.TextField(null=True)),
                ('capex_values', models.TextField(null=True)),
                ('yield_values', models.TextField(null=True)),
                ('turnover_values', models.TextField(null=True)),
                ('net_margin_values', models.TextField(null=True)),
                ('net_results_values', models.TextField(null=True)),
                ('free_cash_flow_values', models.TextField(null=True)),
                ('operating_margin_values', models.TextField(null=True)),
                ('operating_result_values', models.TextField(null=True)),
            ],
        ),
    ]
