# Generated by Django 4.0.6 on 2022-07-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='financial_url',
            field=models.CharField(default='Null', max_length=60),
            preserve_default=False,
        ),
    ]
