# Generated by Django 4.0.6 on 2022-08-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='date_list',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='dividend_hist',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_hist',
            field=models.TextField(null=True),
        ),
    ]
