# Generated by Django 4.0.6 on 2022-08-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stock_date_list_stock_dividend_hist_stock_stock_hist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date_list',
            field=models.DateField(null=True),
        ),
    ]
