# Generated by Django 4.0.6 on 2022-08-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_stock_date_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='date_list',
            new_name='date_dividend',
        ),
        migrations.AddField(
            model_name='stock',
            name='date_hist',
            field=models.TextField(null=True),
        ),
    ]
