# Generated by Django 4.0.6 on 2022-08-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_rename_date_list_stock_date_dividend_stock_date_hist'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='capitalization_values',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='debt_values',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='dividend_distribution_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='equity_values',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='floating_stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='leverage_values',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='sector',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='treasury_values',
            field=models.TextField(null=True),
        ),
    ]
