# Generated by Django 4.0.6 on 2022-08-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_rename_dividend_hist_stock_dividend_values_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='pbr_values',
            field=models.TextField(null=True),
        ),
    ]
