# Generated by Django 4.0.6 on 2022-08-04 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_stock_pbr_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='bpr_values',
        ),
    ]
