# Generated by Django 4.0.6 on 2022-08-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_remove_stock_bpr_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='last_table_date',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='second_table_date',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='years_date',
            field=models.TextField(null=True),
        ),
    ]
